import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import ActionCard from "../components/ActionCard";
import InstructionListCard from "../components/InstructionListCard";
import LinkCard from "../components/LinkCard";

export interface AccountProps {}

const upgradeInstructions = ["Download application form", "Upload Documents"];

const Account: React.FC<AccountProps> = () => {
  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-10 px-10 space-y-10 bg-contentBackground rounded-2xl mr-10 h-5/6 absolute left-[10%] xl:left-[13%] w-[85%]">
        <div>
          <span className="text-white text-2xl font-xs">Account </span>
          <span className="text-white text-2xl font-bold">Settings</span>
        </div>
        <div className="flex space-x-20">
          <div className="space-y-10 w-1/3">
            <div className="flex space-x-5 items-center mb-32">
              <Image
                className="rounded-full cursor-pointer"
                src="/images/profile.png"
                width="100"
                height="100"
                objectFit="cover"
              />
              <div>
                <p className="text-white text-2xl font-xs">Ahmad</p>
                <p className="text-white text-2xl font-bold">D_Zultan</p>
              </div>
            </div>
            <div className="space-y-24">
              <ActionCard description="Used to login into Revallet Account" />
              <InstructionListCard description="To upgrade your account follow these steps:" instructions={upgradeInstructions} />
            </div>
          </div>
          <div className="w-1/3">
            <div className="space-y-5 mb-[70px]">
              <div className="text-white">
                <p className="text-white font-bold">Account Verification</p>
                <p>Provide your identity ddetails and documents scan.</p>
                <p>Verification is needed to apply for prepaid card.</p>
              </div>
              <div className="w-6/12 xl:w-4/12 rounded-3xl bg-gray-300 flex items-center justify-center text-black px-5 py-2 font-bold cursor-pointer hover:bg-gray-400 h-16">
                <p>Verify Account</p>
              </div>
            </div>
            <div className="space-y-24">
              <ActionCard description="Used to login into Wallet Account" />
              <LinkCard
                description="Use this link to invite friends to Wallet"
                link="https://www.crytowallet.com/d_zultan"
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Account;
