import Head from "next/head";
import ActivityList from "../components/ActivityList";
import CardList from "../components/CardList";
import ContentCard from "../components/ContentCard";
import LineGraph from "../components/LineGraph";
import Table from "../components/Table";

let tableData = [
  {
    price: "97,89",
    amount: "2334",
    total: "4234",
  },
  {
    price: "234234",
    amount: "23423",
    total: "23423",
  },
  {
    price: "244234",
    amount: "4324",
    total: "2342",
  },
  {
    price: "244234",
    amount: "4324",
    total: "2342",
  },
  {
    price: "244234",
    amount: "4324",
    total: "2342",
  },
  {
    price: "244234",
    amount: "4324",
    total: "2342",
  },
];

let activityData = [
  {
    name: "Bitcoin",
    start: "9:23:25 PM",
    end: "9:28:25 PM",
    status: "Completed",
  },
  {
    name: "Litecoin",
    start: "6:23:20 AM",
    end: "6:23:25 AM",
    status: "Pending",
  },
];

export default function Home() {
  return (
    <>
    {/* <div className="h-screen bg-mainBackground w-screen overflow-y-hidden font-nunito text-gray-400"> */}
      <Head>
        <title>Cryto Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header /> */}
      {/* <div className="h-screen bg-gradient-to-br from-blue-500 via-gray-500 to-red-500 bg-opacity-30 flex items-center justify-center"> */}
      {/* <main className="flex h-full w-full">
        <SideBar /> */}
        <div className="px-10 left-[10%] xl:left-[13%] absolute w-[85%]">
          <p className="text-white text-2xl font-bold">Dashboard</p>
          <CardList />
          <div className="w-full h-full flex space-x-20 md:py-5 py-10">
            <div className="w-3/5">
              <LineGraph />
              <ActivityList data={activityData} />
            </div>
            <div className="w-2/5 space-y-10">
              <Table data={tableData} />
              <ContentCard />
            </div>
          </div>
        </div>
      {/* </main> */}

      {/* </div> */}
    {/* </div> */}
    </>
  );
}
