import Head from "next/head";
import ActivityList from "../components/ActivityList";
import CardList from "../components/CardList";
import ContentCard from "../components/ContentCard";
import Header from "../components/Header";
import LineGraph from "../components/LineGraph";
import SideBar from "../components/SideBar";
import Table from "../components/Table";

let tableData = [
  {
    price: "97,89",
    amount: "2334",
    total: "4234",
  },
  {
    price: "234234",
    amount: "23423",
    total: "23423",
  },
  {
    price: "244234",
    amount: "4324",
    total: "2342",
  },
  {
    price: "244234",
    amount: "4324",
    total: "2342",
  },
  {
    price: "244234",
    amount: "4324",
    total: "2342",
  },
  {
    price: "244234",
    amount: "4324",
    total: "2342",
  },
];

let activityData = [
  {
    name: "Bitcoin",
    start: "9:23:25 PM",
    end: "9:28:25 PM",
    status: "Completed",
  },
  {
    name: "Litecoin",
    start: "6:23:20 AM",
    end: "6:23:25 AM",
    status: "Pending",
  },
];

export default function Home() {
  return (
    <div className="h-screen bg-mainBackground w-screen overflow-hidden font-nunito text-gray-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {/* <div className="h-screen bg-gradient-to-br from-blue-500 via-gray-500 to-red-500 bg-opacity-30 flex items-center justify-center"> */}
      <main className="flex h-full w-full">
        <SideBar />
        <div className="flex-grow px-10">
          <p className="text-white text-2xl font-bold">Dashboard</p>
          <CardList />
          <div className="w-full h-full bg-yeldlow-400 flex space-x-20 py-10">
            <div className="bg-tedl-400 w-1/2">
              <LineGraph />
              <ActivityList data={activityData} />
            </div>
            <div className="bg-pdink-600 w-2/5 space-y-10">
              <Table data={tableData} />
              <ContentCard />
            </div>
          </div>
        </div>
      </main>

      {/* </div> */}
    </div>
  );
}
